name: Build and Deploy via FTP

on:
  push:
    branches: [main]  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or your app's Node version

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build static site (Next.js with output: 'export')
        run: |
          cd client
          npm run build
        env:
          NEXT_PUBLIC_BACKEND_HOST: ${{ secrets.NEXT_PUBLIC_BACKEND_HOST }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./client/out
          server-dir: htdocs/
          dangerous-clean-slate: true
          exclude: |
            .htaccess
          log-level: verbose
